const destinations = [
  {
    id: 1,
    name: "Pantai Kuta",
    location: "Bali",
    category: "Pantai",
    rating: 4.3,
    price: 50000,
    description: "Pantai terkenal di Bali dengan pasir putih dan sunset indah.",
    facilities: ["Parkir", "Toilet", "Kantin"],
    image: "images/pantai-kuta.jpg",
  },
  {
    id: 2,
    name: "Candi Borobudur",
    location: "Magelang",
    category: "Sejarah",
    rating: 4.7,
    price: 75000,
    description:
      "Candi Buddha terbesar di dunia dengan pemandangan menakjubkan.",
    facilities: ["Pemandu", "Toilet", "Museum"],
    image: "images/candi-borobudur.jpg",
  },
  {
    id: 3,
    name: "Keraton Yogyakarta",
    location: "Yogyakarta",
    category: "Sejarah",
    rating: 4.2,
    price: 30000,
    description: "Istana resmi Kesultanan Ngayogyakarta Hadiningrat.",
    facilities: ["Pemandu", "Parkir", "Toilet"],
    image: "images/keraton-jogja.jpg",
  },
  {
    id: 4,
    name: "Pantai Senggigi",
    location: "Lombok",
    category: "Pantai",
    rating: 4.1,
    price: 40000,
    description: "Pantai dengan panorama gunung dan laut yang memukau.",
    facilities: ["Parkir", "Toilet", "Warung"],
    image: "images/pantai-senggigi.jpg",
  },
  {
    id: 5,
    name: "Raja Ampat",
    location: "Papua Barat",
    category: "Alam",
    rating: 4.9,
    price: 150000,
    description: "Kepulauan dengan kekayaan bawah laut terbaik dunia.",
    facilities: ["Tour Guide", "Penginapan", "Toilet"],
    image: "images/raja-ampat.jpg",
  },
  {
    id: 6,
    name: "Bantimurung",
    location: "Sulawesi Selatan",
    category: "Alam",
    rating: 4.4,
    price: 20000,
    description: "Taman nasional terkenal dengan air terjun dan kupu–kupu.",
    facilities: ["Parkir", "Toilet", "Penginapan"],
    image: "images/bantimurung.jpg",
  },
  {
    id: 7,
    name: "Tana Toraja",
    location: "Sulawesi Selatan",
    category: "Budaya",
    rating: 4.6,
    price: 80000,
    description: "Daerah budaya dengan upacara adat dan rumah tongkonan.",
    facilities: ["Pemandu", "Penginapan", "Toilet"],
    image: "images/tana-toraja.jpg",
  },
  {
    id: 8,
    name: "Kawah Ijen",
    location: "Jawa Timur",
    category: "Alam",
    rating: 4.5,
    price: 60000,
    description: "Gunung berapi dengan blue fire dan danau asam.",
    facilities: ["Guide", "Parkir", "Warung"],
    image: "images/kawah-ijen.jpg",
  },
];

const bookings = [];

const users = [{ username: "adit", password: "adit123" }];

module.exports = { destinations, bookings, users };
